server:
    port: 9000
spring:
    application:
        name: cp-raid-manager-system-controller-app
    main:
        allow-bean-definition-overriding: true
        web-application-type: reactive
    #couchbase:
        #connection-string: localhost
        #username: user
        #password: password
    data:
        #couchbase:
            #bucket-name: RAID_MANAGER_AGGREGATES
            #repositories:
                #type: reactive
        mongodb:
            repositories:
                type: reactive
            uri: mongodb://username:password@localhost:27017/RAID_MANAGER_DB?authSource=admin&authMechanism=SCRAM-SHA-1
    mail:
        test-connection: off
        host: smtp_host
        port: 587
        username: username
        password: password
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
                    starttls:
                        enable: true


---

raid-manager:
    security:
        allow-credentials: true
        allowed-origins:
            - http://localhost:3000
        allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
        allowed-headers:
            - Content-Type
            - Authorization
        exposed-headers:
            - Content-Type
            - Authorization
    jwt:
        header-key: Authorization
        prefix: "Bearer "
        expiration: 604800
        secret: superXsecureXdevXsecretXsuperXsecureXdevXsecretXsuperXsecureXdevXsecretXsuperXsecureXdevXsecret
    app:
        artificial-delay-ms: 1000