pipeline {

    environment {
        ROOT = "cp-raid-manager-system-controller-app"
        NAME = "cp-raid-manager-system-controller-app"
        MVN_TO_USE = "maven-3.6.3"
        JDK_TO_USE = "jdk-11"

        MONGODB_USERNAME = credentials('mongodb-username')
        MONGODB_PASSWORD = credentials('mongodb-password')
        JWT_SECRET = credentials('jwt-secret')
    }

    agent any

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    parameters {
        string(name: 'VERSION', description: 'Docker image version to deploy')
        string(name: 'MONGODB_HOST', defaultValue: 'raid-manager-mongo', description: 'Hostname for mongodb')
        string(name: 'MONGODB_PORT', defaultValue: '27017', description: 'Port for mongodb')
        string(name: 'MONGODB_DATABASE', defaultValue: 'RAID_MANAGER_DB', description: 'Database name for mongodb')
        string(name: 'ARTIFICIAL_DELAY_MS', defaultValue: '0', description: 'Artificial delay to apply (in ms)')
        string(name: 'ALLOWED_ORIGINS', defaultValue: 'https://dodo.cp-sys.hu', description: 'Comma separated list of allowed origins')
        string(name: 'PROXY', defaultValue: 'pigeon-nginx', description: 'Name of the container to reload after operations')
    }

    stages {
        stage ('Preparation') {
            steps {
                deleteDir()
                checkout scm
            }
        }

        stage ('Remove existing') {
            steps {
                script {
                    sh "docker container rm ${env.NAME} -f"
                }
            }
        }

        stage ('Docker run') {
            steps {
                script {
                    docker.withRegistry('http://build.cp-sys.hu', 'pigeon-nexus') {
                        def cmd = "docker run -d ";
                        cmd += "--network=\"raid-manager\" "
                        cmd += "--name ${env.NAME} "
                        cmd += '-e \"SPRING_DATA_MONGODB_URI=mongodb://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_HOST:$MONGODB_PORT/$MONGODB_DATABASE?authSource=admin&authMechanism=SCRAM-SHA-1\" '
                        cmd += "-e \"RAIDMANAGER_APP_ARTIFICIALDELAYMS=${params.ARTIFICIAL_DELAY_MS}\" "
                        cmd += "-e \"RAIDMANAGER_SECURITY_ALLOWEDORIGINS=${params.ALLOWED_ORIGINS}\" "
                        cmd += '-e \"RAIDMANAGER_JWT_SECRET=$env.JWT_SECRET\" '
                        cmd += "build.cp-sys.hu/${env.NAME}:${params.VERSION}"

                        sh "${cmd}"
                    }
                }
            }
        }

        stage ('Reload proxy') {
            steps {
                script {
                    sh "docker container restart -t 2 ${params.PROXY}"
                }
            }
        }
    }
}
