
pipeline {

    agent any

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages {
        stage ('Preparation') {
            steps {
                deleteDir()
                checkout scm
            }
        }

        stage ('Maven package') {
            steps {
                sh 'pwd'
                sh 'mvn -f cp-raid-manager-system-controller-app/pom.xml  clean package'
            }
        }
    }
}