
pipeline {

    environment {
        ROOT = "cp-raid-manager-system-controller-app"
    }

    agent any

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages {
        stage ('Preparation') {
            steps {
                deleteDir()
                checkout scm
            }
        }

        stage ('Maven package') {
            steps {
                withMaven(maven: "maven-3.6.3", jdk: "jdk-11") {
                    sh "mvn -f ${env.ROOT}/pom.xml clean package"
                }
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }

        stage ('Maven deploy') {
            steps {
                withMaven(maven: "maven-3.6.3", jdk: "jdk-11") {
                    sh "mvn -DskipTests=true -f ${env.ROOT}/pom.xml deploy"
                }
            }
        }
    }
}
